#Data neural Prophet
parameters_model:
  growth: "linear"
  n_changepoints: 10
  seasonality_mode: "additive"
  loss_func: "MAE"
  trend_reg_threshold: True
  yearly_seasonality: "auto"
  weekly_seasonality: "auto"
  daily_seasonality: "auto"
  epochs: 1000
  accelerator: "cuda"
  batch_size: 1024

name: "temperature_neural_prophet_20_june_backup.pkl"
base_dataset: "../../Datasets/dataset_TPV/base_pump_23042023_A_resampled_10min"
select_feature: "temperature"
time: "Time"

predict_in_the_future: 5118 # 3000