
parameters_model:
  growth: "discontinuous"
  n_changepoints: 10
  seasonality_mode: "multiplicative"
  loss_func: "MAE"
  trend_reg_threshold: True
  weekly_seasonality: True
  daily_seasonality: True
  epochs: 1

base_dataset: "../../Datasets/dataset_TPV/base_pump_23042023_A_resampled_10min"
select_feature: "temperature"
time: "Time"