#Data neural Prophet
parameters_model:
  train: True
  growth: "linear"
  n_changepoints: 10
  seasonality_mode: "additive"
  loss_func: "MAE"
  trend_reg_threshold: True
  yearly_seasonality: "auto"
  weekly_seasonality: "auto"
  daily_seasonality: "auto"
  epochs: 1000
  accelerator: "cuda"
  batch_size: 1024

name: "temperature_neural_prophet_21_june_sensor.pkl"
base_dataset: "../../Datasets/dataset_TPV/base_pump_23042023_A_resampled_10min"
select_feature: "temperature"
time: "Time"

predict_in_the_future: 2869 # 3000

plot_config:
  x_axis: "x_axis"
  y_axis: "y_axis"
  title: "forecast"
  length_circle: 0.5
  select_feature: "temperature"