context_size: 2
batch_size_train: 256
batch_size_valid: 64
learning_rate: 0.00005
epochs: 20

# ----- Config LSTM Model
LSTM_config:
  hidden_dim: 128
  num_layers: 15
  output_dim: 2

#----- Train test split
train_test_split:
  test_size: 0.15
  random_state: 42

#----- wandb
wandb: true
