# context_size: 20000
context_size: 20000
batch_size_train: 512
batch_size_valid: 64
learning_rate: 0.00005
epochs: 1
name_model: 'model_batch_512.h5'
# ----- Config LSTM Model
LSTM_config:
  hidden_dim: 127
  num_layers: 5
  output_dim: 2

#----- Train test split
train_test_split:
  test_size: 0.15
  random_state: 42

#----- wandb
wandb: True
