network: "transformer_sintetic_soft_dtw"
#-----Organize train, test, validation
train_batch_size: 1

valid_batch_size: 1

test_batch_size: 1

learning_rate: 0.00005

reload_model:
  type: False
  data: "9_fev"

model:
  TimeSeriesTransformers:
    n_encoder_layers: 5
    n_decoder_layers: 5

optimizer:
  Adam:
    lr: 0.0001
    weight_decay: 0.01

loss:
  soft_dtw: soft_dtw
  # KullbackLeibler: KullbackLeibler

epochs: 150

#----- Train test split
train_test_split:
  test_size: 0.15
  random_state: 42

#--- path save model
path_save_model: 'models_h5/'
name_model: 'model_batch_4.h5'


evaluate_step: 1000

schedule: 100

#----- wandb
wandb: True

#---- DIR dataset mafaulda
train_dataset:
  DatasetSinteticUnsupervisedLSTM:
    dir_data: 'Datasets/sintetic_data/train_compressor_data.h5'
    context: 100
    stride: 1

valid_dataset:
  DatasetSinteticUnsupervisedLSTM:
    dir_data: 'Datasets/sintetic_data/test_compressor_data.h5'
    context: 100
    stride: 1

test_dataset:
  DatasetSinteticUnsupervisedLSTM:
    dir_data: 'Datasets/sintetic_data/test_compressor_data.h5'
    context: 100
    stride: 1

path_to_save_model: 'model_h5/'
